add priest behavior with an example
Game-as-a-Service/LoveLetter pull request #25
Opened 2022-12-01 10:46 UTC by FuyaosGithub

有個問題在這邊討論一下
昨天提到Player類別需要新增存放看了「誰」的「手牌」，因此有在該類別底下新增兩個屬性代表曾經看過誰與手牌
(可在code_review時看看是否要在包成一個dictionary 代表key, value pair)
因此在feature中將Then 寫成：{玩家A} 看到了玩家B的公主 (只有玩家A是變數，並且判斷「誰」、「手牌」是否為空)

另外這邊註記寫成List的形式後，在通知的地方就要去判斷這是第一次還是第二次。不然就會出現
第一次提示：
* 玩家A 透過神父私下看了玩家B 的卡片 公主
第二次提示： (多提示了之前的情況）
* 玩家A 透過神父私下看了玩家B 的卡片 公主
* 玩家A 透過神父私下看了玩家C 的卡片 國王

2022-12-01 10:57 UTC, qrtt1 commented
提示其實沒有重複的問題

1. 如果是整個 UI View 被 update，其實使用者最後看到的是 2 筆 (比原先 1 筆多出 1 數)
2. 如果是 send event 的方式，那就是加入前去 send event，也不會重送訊息 (儘管，目前還沒開始這部分的計劃)

2022-12-01 11:05 UTC, qrtt1 commented on features/steps/common.py
> +
1. `玩家B` 與 `公主` 都應該是參數進來。
2. 實作中沒有去檢查 `玩家A` 看到的內容。

2022-12-01 11:06 UTC, qrtt1 commented on love_letter/models/cards.py
> +
這裡好像沒有實作？是不是有程式還沒推上來？

2022-12-01 14:19 UTC, IamSaker commented on love_letter/models/__init__.py
參考

```python
from dataclasses import dataclass


@dataclass
class Seen:
    opponent: str
    card: Card

class Player:

    def __init__(self):
        ...
        self.seen_cards: list[Seen] = []
```

2022-12-01 14:22 UTC, qrtt1 commented on love_letter/models/__init__.py
學習惹！還沒用過，偶好興奮R

2022-12-01 23:59 UTC, qrtt1 requested changes

2022-12-01 23:59 UTC, qrtt1 commented on features/steps/common.py
> +
不需要的程式就刪除，不用註解起來。

2022-12-01 23:59 UTC, qrtt1 commented on features/steps/common.py
> +    assert active_player.is_seen_opponent_card(inactive_player, card_will_be_checked) is True
應該直接檢查 `seen_cards`

`is_seen_opponent_card` 對 Player 本身不是 business logic 需要的，它只有測試會用到。可以考慮搬到 `common.py` 或是把它實作的邏輯搬至此 method 內就好。

2022-12-01 23:59 UTC, qrtt1 commented on features/steps/common.py
> +def player_get_opponent_hand(context, player_a, player_b, card):
`player_get_opponent_hand` -> `player_saw_opponent_hand`

2022-12-01 23:59 UTC, qrtt1 commented on love_letter/models/__init__.py
> +    def is_seen_opponent_card(self, opponent: "Player", card_will_be_checked: "Card"):
`is_seen_opponent_card` 是來自測試的需求，不是 business logic。所以，它放在測試中較為適當。

2022-12-02 05:28 UTC, qrtt1 approved these changes

2022-12-02 05:28 UTC, qrtt1 commented on love_letter/models/cards.py
> +
這裡的實目前是 `曝露` 在 https://github.com/Game-as-a-Service/LoveLetter/pull/25/files#diff-670aa5c31422b26c5b3d1185ea2ae26930f0f16e5bbe8e03b71828a4058674f5R120-R123

也就是它的 caller `Player` 身上，但實際上責任在於 Card 觸發效果本身。無奈目前的結構沒辦法支援這事件，得要在 [重構後的版本](https://github.com/Game-as-a-Service/LoveLetter/pull/26) 才能把實作放回 Card 本身了。

目前只能暫時接受這個 PR。

2022-12-02 05:29 UTC, merged

2022-12-02 05:42 UTC, qrtt1 commented on love_letter/models/cards.py
> +
已在重構 branch 轉換好實作
https://github.com/Game-as-a-Service/LoveLetter/pull/26/commits/283d1f1bcd7e0c3791374d9584158b61fbe2deaf

2022-12-04 16:01 UTC, s9891326 commented on features/priest.feature
> +    Then 玩家A 看到了 玩家B 的 公主
剛剛發現這個是不是要補一個Scenario `玩家出牌 對手被侍女保護中`