add handmaid behave
Game-as-a-Service/LoveLetter pull request #27
Opened 2022-12-02 03:45 UTC by FuyaosGithub

提交了侍女behave

2022-12-02 05:45 UTC, qrtt1 requested changes
我先將 merge 的 base 改為 `refactor/discarding_a_card_method`

請將此 branch 的 base 也換位為 `refactor/discarding_a_card_method` 

```sh
git fetch
git rebase -i origin/refactor/discarding_a_card_method
```

修好了 conflict 後，再推一次 source code 上來 :D

2022-12-02 07:24 UTC, IamSaker approved these changes

2022-12-02 09:39 UTC, qrtt1 commented
進度報告，由於 `巨大的` refactoring 已經完成 merge。我再度將這個 PR 的 base 切回 `master`，剩下的只要解 conflict 就行了 :D

2022-12-02 14:43 UTC, s9891326 commented
> 進度報告，由於 `巨大的` refactoring 已經完成 merge。我再度將這個 PR 的 base 切回 `master`，剩下的只要解 conflict 就行了 :D

這個要怎麼

2022-12-02 14:46 UTC, s9891326 commented
按錯抱歉XD

2022-12-02 14:46 UTC, s9891326 approved these changes
LSTM

2022-12-02 15:34 UTC, qrtt1 approved these changes

2022-12-03 09:06 UTC, FuyaosGithub commented
解決重構之後的conflict、並且重新測試過behave且ＰＡＳＳ

2022-12-04 01:53 UTC, merged