add king behave
Game-as-a-Service/LoveLetter pull request #31
Opened 2022-12-04 11:21 UTC by FuyaosGithub

國王的example mapping

2022-12-05 05:22 UTC, IamSaker commented on features/king.feature
> +    Then 玩家B 手牌為 侍女
Scenario 的描述寫錯囉！
然後，可以再多一個 Scenario 是
玩家 B 有侍女保護，玩家 A 出了國王後，什麼也不會發生

2022-12-05 05:22 UTC, IamSaker commented on love_letter/models/cards.py
> +        card_holder.cards.append(chosen_player_hand_card)
這一段 filter 是為了什麼？
```python
card_holder_left_hand_card = list(filter(lambda x: x.name != self.name, card_holder.cards))
```

2022-12-05 05:22 UTC, IamSaker commented on love_letter/models/cards.py
> +        card_holder.cards.append(chosen_player_hand_card)
如果是單純 swap，可以這樣使用（以下為 pseudo code）
```python
chosen_player.cards[0], card_holder.cards[0] = card_holder.cards[0], chosen_player.cards[0]
```

2022-12-05 07:16 UTC, FuyaosGithub commented on love_letter/models/cards.py
> +        card_holder.cards.append(chosen_player_hand_card)
> 這一段 filter 是為了什麼？
> 
> ```python
> card_holder_left_hand_card = list(filter(lambda x: x.name != self.name, card_holder.cards))
> ```

因為card_holder手上有兩張手牌，要找出非國王的那張牌

2022-12-05 07:18 UTC, FuyaosGithub commented on love_letter/models/cards.py
> +        card_holder.cards.append(chosen_player_hand_card)
> 如果是單純 swap，可以這樣使用（以下為 pseudo code）
> 
> ```python
> chosen_player.cards[0], card_holder.cards[0] = card_holder.cards[0], chosen_player.cards[0]
> ```

那這樣有個疑問就是：要如何確定card_holder的國王是在list內的索引[0]還是索引[1]呢?

2022-12-05 07:31 UTC, FuyaosGithub commented on love_letter/models/cards.py
> +        card_holder.cards.append(chosen_player_hand_card)
> 如果是單純 swap，可以這樣使用（以下為 pseudo code）
> 
> ```python
> chosen_player.cards[0], card_holder.cards[0] = card_holder.cards[0], chosen_player.cards[0]
> ```

嘗試以swap 寫法寫看看，不知道這樣是否比較容易懂呢?
chosen_player_hand_card = chosen_player.cards[0]

card_holder_left_hand_card = card_holder_left_hand_card = list(filter(lambda x: x.name != self.name, card_holder.cards))

chosen_player_swap_card_index = card_holder.cards.index('card_holder_left_hand_card')

chosen_player.cards[0], card_holder.cards[chosen_player_swap_card_index] = card_holder.cards[chosen_player_swap_card_index],chosen_player.cards[0]

2022-12-05 07:35 UTC, FuyaosGithub commented on love_letter/models/cards.py
> +        card_holder.cards.append(chosen_player_hand_card)
> 如果是單純 swap，可以這樣使用（以下為 pseudo code）
> 
> ```python
> chosen_player.cards[0], card_holder.cards[0] = card_holder.cards[0], chosen_player.cards[0]
> ```

嘗試以swap 去寫，不知道這樣寫法有沒有比較容易理解呢?


card_holder_left_hand_card = list(filter(lambda x: x.name != self.name, card_holder.cards))
chosen_player_swap_card_index = card_holder.cards.index(card_holder_left_hand_card[0])
chosen_player.cards[0], card_holder.cards[chosen_player_swap_card_index] = card_holder.cards[chosen_player_swap_card_index],chosen_player.cards[0]

2022-12-05 16:38 UTC, IamSaker commented on love_letter/models/cards.py
> +        card_holder.cards.append(chosen_player_hand_card)
瞭解，兩種寫法你再擇一吧！

2022-12-07 16:27 UTC, IamSaker approved these changes

2022-12-07 16:47 UTC, merged

2022-12-07 16:50 UTC, qrtt1 requested changes

2022-12-08 01:11 UTC, IamSaker commented on features/king.feature
> +    Then 玩家B 未出局
沒錯，終於被 @qrtt1 看懂且翻譯翻譯，原來是我表達的不夠清楚😓

2022-12-08 01:20 UTC, qrtt1 commented on features/king.feature
> +    Then 玩家B 未出局
新的實作在這個，有空也可以看一下 
https://github.com/Game-as-a-Service/LoveLetter/pull/39

2022-12-08 03:06 UTC, FuyaosGithub reviewed
test