[TDD] 經過了一回合後，侍女的保護失效
Game-as-a-Service/LoveLetter pull request #34
Opened 2022-12-06 09:51 UTC by s9891326

- #33 ，目前先用BDD的方式完善侍女規則(忽略其他玩家對保護者的卡片效果)

2022-12-07 16:28 UTC, qrtt1 requested changes
期望能減化測試，縮到由 domain layer 端的測試。

2022-12-07 16:28 UTC, qrtt1 commented on tests/test_lose_handmaid_protected.py
> +class LostHandMaidProtected(unittest.TestCase):
這樣寫有一點苦，因為 player-context 本身還不太穩定 (之後會一直變動)。我會期望 e2e 的情境先縮小在 walking skeleton 那就好。不然，之後要改的 player-context 很多，會頭很大呦。

也許先搭便車，接在 Game 的固定規則 branch 後，用那邊的寫法來測呢？
https://github.com/Game-as-a-Service/LoveLetter/pull/36

2022-12-08 08:10 UTC, IamSaker approved these changes

2022-12-09 00:47 UTC, qrtt1 approved these changes

2022-12-09 01:36 UTC, merged