fix bug - guard could not guess guard
Game-as-a-Service/LoveLetter pull request #38
Opened 2022-12-07 17:03 UTC by FuyaosGithub

fix bug - guard could not guess guard

2022-12-07 23:46 UTC, qrtt1 requested changes
需要有 testcast 來驗證它。

可以補在 `guard.feature`

2022-12-09 01:33 UTC, qrtt1 requested changes

2022-12-09 01:33 UTC, qrtt1 commented on love_letter/models/cards.py
> +        if with_card == GuardCard:
object instance 與 class 相比不會相等，得使用 `isinstance`

https://docs.python.org/3/library/functions.html#isinstance

2022-12-15 08:07 UTC, IamSaker commented on love_letter/models/cards.py
> +        if with_card == GuardCard:
再麻煩 @FuyaosGithub 調整
```python
if with_card == GuardCard isinstance(:
```

2022-12-16 08:23 UTC, FuyaosGithub commented on love_letter/models/cards.py
> +        if with_card == GuardCard:
okok

2022-12-20 07:06 UTC, FuyaosGithub commented on love_letter/models/cards.py
> +        if with_card == GuardCard:
> 再麻煩 @FuyaosGithub 調整
> 
> ```python
> if isinstance(with_card, GuardCard):
>     return False
> ```

此處已修正

2022-12-20 07:24 UTC, IamSaker approved these changes

2022-12-20 07:49 UTC, qrtt1 approved these changes

2022-12-20 07:49 UTC, merged