add test: when there is only one player, then the player is winner and get one token of affection
Game-as-a-Service/LoveLetter pull request #58
Opened 2022-12-19 15:39 UTC by Zeng9898

add test: when there is only one player, then the player is winner and get one token of affection

todo: when deck has no card, need to judge who is the winner

2022-12-20 01:54 UTC, qrtt1 requested changes

2022-12-20 01:54 UTC, qrtt1 commented on love_letter/models/__init__.py
>              self.next_round(winner_name)
might_has_winner 的邏輯變多了，是時候獨立成 1 個 method 了 :D

```python
if self.find_the_winner():
  return
```

在 `find_the_winner` 中就是要放 155 ~ 162 原本要實作的內容。

2022-12-20 01:54 UTC, qrtt1 commented on love_letter/models/__init__.py
> +                    player.tokens_of_affection += 1
目前的分數記錄，有變更到 player 總表的位置。在實作細節提醒中，有提到 https://github.com/Game-as-a-Service/LoveLetter/issues/41#issuecomment-1344151564

* `局` round 內的 player 也需要更新，作為歷史記錄之用 (未實作)
* `遊戲` game 內的 player 會被更新，作為最新的分數記錄之用 (已實作)

2022-12-20 01:54 UTC, qrtt1 commented on tests/test_card_behave.py
> +        self.assertEqual('1', self.game.rounds[-1].turn_player.name)  # turn player of this round
需要測試 winner 在 `rounds` 與 `game` 中的分數是一致的。

2022-12-20 07:48 UTC, IamSaker commented on love_letter/models/__init__.py
> +                    player.tokens_of_affection += 1
```python
winner_name = might_has_winner[0].name
    for player in self.players:
        if player.name == winner_name:
            player.tokens_of_affection += 1
```

2022-12-20 07:48 UTC, IamSaker commented on tests/test_card_behave.py
> +        此局結束 玩家1 獲得一枚好感指示物
敘述有誤，「玩家2 對 玩家1」、「 玩家2 獲得一枚好感指示物」比較合理

2022-12-20 07:48 UTC, IamSaker commented on tests/test_card_behave.py
> +        此局結束 玩家1 獲得一枚好感指示物
或是改成「玩家2 出局」即可

2022-12-25 07:39 UTC, qrtt1 commented on love_letter/models/__init__.py
> +            for player in self.players:
這些看起來很像的 code 會存在，是因為在「決策匯流」之前分別實作了。winner 的產生方式有 2 種，但無論哪一種都會進入到 `下一局` Command，所以看起來把計分的邏輯，包含在 ` self.next_round(winner_name)` 之中會較為合理。

同樣的，結束遊戲的條件也會因為在 ` self.next_round(winner_name)` 時決定，也應該包含在裡面，看看是否該 `下一局` 還是 `遊戲結束`

2023-01-01 06:34 UTC, qrtt1 approved these changes

2023-01-01 06:39 UTC, merged