增加black、isort套件
Game-as-a-Service/LoveLetter pull request #63
Opened 2022-12-26 09:44 UTC by s9891326

- 引入`black`、`isort`套件來管理我們的專案格式、排版
- 引入`pre-commit`的方式，讓我們在commit的時候就會自己幫你觸發上面兩個套件了，觸發完後會自動幫你處理好，再次commit就能正常commit了。(當pre-commit的時候必須要有對應的套件才會正常觸發)

```shell
# 安裝套件
poetry install

# 將 pre-commit hook 安裝至專案裡的 .git/hooks 資料夾底下
pre-commit install --install-hooks

# 開始開發程式碼~ 開發完成後進行commit
git commit

# 就會觸發到那兩個套件，如果有問題，會自動幫你修正
```

2022-12-26 13:07 UTC, qrtt1 requested changes
1. formatter 的測試要在 CI 上執行，即使 local 沒有遵守也會被擋下來。
2. 需要提供 IDE 整合的方式，至少 black 要取代原本的 formatter，才不會每次都要重新用 black formatter

black 官方有整合的文件，可以補在 readme
https://black.readthedocs.io/en/stable/integrations/editors.html

2022-12-26 14:53 UTC, s9891326 commented
> 1. formatter 的測試要在 CI 上執行，即使 local 沒有遵守也會被擋下來。
- 恩恩我看別人也是會在CI上面也設一套。但我自己測下來commit一定要遵守他的規範才給我commit耶，有什麼強制commit的語法嗎?

> 2. 需要提供 IDE 整合的方式，至少 black 要取代原本的 formatter，才不會每次都要重新用 black formatter
- 原來有這東西啊XD，設定完成後會把原本的`CTRL + Alt + L`的也換成black

2022-12-27 02:19 UTC, qrtt1 commented
> > 1. formatter 的測試要在 CI 上執行，即使 local 沒有遵守也會被擋下來。
> 
> * 恩恩我看別人也是會在CI上面也設一套。但我自己測下來commit一定要遵守他的規範才給我commit耶，有什麼強制commit的語法嗎?


像我 local 是單純用 `venv` 他就不會觸發，或是我沒有自己裝好 `pre-commit` 的情況。主要的點在於，不管開發者有沒有完成他在 local 應該有的設置，得有主要的守門員來擋住它。

如果一個不符合期待的程式，可以進得到 repo 內。那肯定流程上是有問題的，這種情況特別會發生在「流程交替」之中，或「新加入的開發者」並不知情的典型情境。

所以，無論是什麼原因，透過 CI 去阻擋，並給予修改的指示 (文件) 或不知道如何修改去找人求助。才會讓每個開發者的環境漸趨符合期待。

2022-12-29 02:23 UTC, s9891326 commented
這個我重開一個branch好了，先把其他人的都先合進來，我再把這個用一用

2022-12-29 02:23 UTC, closed without merging

2022-12-29 02:42 UTC, qrtt1 commented
可以先在群內，跟大家約個時間 :D