Resolve most of the typing warnings.
Game-as-a-Service/LoveLetter pull request #64
Opened 2022-12-28 12:37 UTC by iannbing

開專案時，從我的編輯器(VS Code)裡面開專案看到很多typing的警告。
這個PR清理掉大部分的警告，除了少數一些在test裡面的dict。

2022-12-28 13:12 UTC, s9891326 commented on love_letter/models/__init__.py
> +        self.__name = value
想問一下 `__name` 這樣的命名是有什麼想法呢?
我看下面的介紹是防止子類引用
![image](https://user-images.githubusercontent.com/44540755/209817471-8c418406-6e34-4ef1-a975-3c6aec6d75f2.png)

2022-12-28 13:45 UTC, iannbing commented on love_letter/models/__init__.py
> +        self.__name = value
嗯嗯，或許前單底線就足夠了 👍。
這邊其實我不是很確定，主要是因為`name`是`create`時才給的。
如果在`__init__`時就直接要求要給`name`，那這些code是完全不必要的，`@classmethod create`也可以一併刪除。
我先推個commit照我的想法實作，如果有其他我沒考慮到的點，我再rollback 😄。

2022-12-28 13:52 UTC, iannbing commented on love_letter/models/__init__.py
> +        self.__name = value
@s9891326 詳見[此commit](https://github.com/Game-as-a-Service/LoveLetter/pull/64/commits/20b51ada800d70f9cbbfa49094d9846545859167)。

2022-12-28 14:45 UTC, iannbing commented on love_letter/models/__init__.py
> +        self.__name = value
我順手也把其他在test裡的錯誤清掉了。

2022-12-29 01:44 UTC, s9891326 approved these changes
LGTM

2022-12-29 01:50 UTC, YYLIZH commented on tests/test_card_behave.py
> +def reset_deck(card_name_list: List[str], remove_by_rule_cards: List[str] = []):
Hello, 在網路上看到你們的repo，覺得很好玩，不好意思冒昧留了意見。

這邊的function修成這樣的話，如果拿去跑pylint的話會叫。https://pylint.pycqa.org/en/latest/user_guide/messages/warning/dangerous-default-value.html
https://stackoverflow.com/a/26320938

原本的做法才是對的喔~~

2022-12-29 02:08 UTC, s9891326 commented on tests/test_card_behave.py
> +def reset_deck(card_name_list: List[str], remove_by_rule_cards: List[str] = []):
感謝提醒XD 熊熊給他忘記了

2022-12-29 02:10 UTC, qrtt1 requested changes
`reset_deck` 的部分要還原成原本的實作。

2022-12-29 02:10 UTC, qrtt1 commented on tests/test_card_behave.py
> +def reset_deck(card_name_list: List[str], remove_by_rule_cards: List[str] = []):
`reset_deck` 的 `remove_by_rule_cards` 真的不能這樣寫，要用原本的寫法。

https://www.toptal.com/python/top-10-mistakes-that-python-programmers-make

other references:
1. https://discord.com/channels/937992003415838761/1049972962540916867
2. https://www.v2ex.com/t/467817

2022-12-29 09:40 UTC, iannbing commented on tests/test_card_behave.py
> +def reset_deck(card_name_list: List[str], remove_by_rule_cards: List[str] = []):
@YYLIZH @qrtt1 感謝提醒! 詳見此[commit](https://github.com/Game-as-a-Service/LoveLetter/pull/64/commits/58d51c4997bc0694d435f205f53cdd3dab9e0bc1)。

2022-12-29 11:33 UTC, qrtt1 approved these changes

2022-12-29 11:38 UTC, merged